name: TheSchwartz
version: 1.03
author: Six Apart <cpan@sixapart.com>
license: perl
distribution_type: module
requires:
  Data::ObjectDriver: 0.03
  Digest::MD5: 0
  Storable: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
