---
author:
  - 'Six Apart <cpan@sixapart.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TheSchwartz
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::ObjectDriver: 0.04
  Digest::MD5: 0
  Storable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.10
